### ISSUE TITLE
[Bug] Broken links in README.md and CONTRIBUTING.md

### ISSUE THREAD

**Issue by manucorujo** [InditexTech/foss#9]
# Bug description

The 4 links in the `README.md` to the Manifesto are broken, because the name of the Manifesto file is `INDITEX_FOSS_Manifesto.md` but the link leads to `ITX_FOSS_Manifesto.md`. This causes a 404 error when clicking on the link.

In addition, the link to `CODE_OF_CONDUCT.md` in the `CONTRIBUTING.md` is also broken, as the file name is `CODE_of_CONDUCT.md` ("of" in lower case) and the link leads to `CODE_OF_CONDUCT.md` ("OF" in upper case).

# Proposed solution

Both problems can be solved either by changing the link (from `https://github.com/InditexTech/foss/blob/main/ITX_FOSS_Manifesto.md` to `https://github.com/InditexTech/foss/blob/main/INDITEX_FOSS_Manifesto.md` in the first case) or by changing the file name (from `INDITEX_FOSS_Manifesto.md` to `ITX_FOSS_Manifesto.md`).

The second option may be more risky, as there may be links that are properly referencing the file, and these may be broken when the file is renamed. For example, `CODE_of_CONDUCT.md` is well referenced from `README.md`. So, if the second option is chosen, care should be taken to change, in addition to the filename, all working links to the file.

**Comment by jsmanrique** [comment]
**Thank you** so much for highlighting this issue and the detailed solutions proposals 😍 

I would recommend going with the first solution proposed: changing the link to the right file name.
